# Generated by Django 2.2.20 on 2022-09-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
