# Generated by Django 2.2.20 on 2022-09-16 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message="Username должен содержать только буквы, цифры и символы: '@', '.', '+', '-', '_'", regex='^[\\w.@+-]+\\Z')], verbose_name='Логин'),
        ),
    ]
