# Generated by Django 2.2.20 on 2022-09-16 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220916_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message="Username должен содержать только буквы, цифры и символы: '@', '.', '+', '-', '_'", regex='^[\\w.@+-]+\\Z')], verbose_name='Логин'),
        ),
    ]
