# Generated by Django 2.2.20 on 2022-09-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220916_2005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
